export const liveData = [
  {
    home: "Nottingham Forest",
    away: "Manchester United",
    homeScore: 2,
    awayScore: 1,
    minutesPlayed: 65,
    status: "Live",
    id: 1,
  },
  {
    home: "Team A",
    away: "Team B",
    homeScore: 0,
    awayScore: 0,
    minutesPlayed: 20,
    status: "Finished",
    id: 2,
  },
  {
    home: "Team X",
    away: "Team Y",
    homeScore: 1,
    awayScore: 2,
    minutesPlayed: 45,
    status: "Live",
    id: 3,
  },
  {
    home: "Team Alpha",
    away: "Team Beta",
    homeScore: 3,
    awayScore: 3,
    minutesPlayed: 80,
    status: "Live",
    id: 4,
  },
  {
    home: "Team Red",
    away: "Team Blue",
    homeScore: 2,
    awayScore: 1,
    minutesPlayed: 75,
    status: "Finished",
    id: 5,
  },
  {
    home: "Team One",
    away: "Team Two",
    homeScore: 0,
    awayScore: 1,
    minutesPlayed: 55,
    status: "Upcoming",
    id: 6,
  },
  {
    home: "Team A",
    away: "Team B",
    homeScore: 1,
    awayScore: 2,
    minutesPlayed: 30,
    status: "Upcoming",
    id: 7,
  },
  {
    home: "Team Red",
    away: "Team Green",
    homeScore: 1,
    awayScore: 0,
    minutesPlayed: 40,
    status: "Upcoming",
    id: 8,
  },
  {
    home: "Team Home",
    away: "Team Away",
    homeScore: 2,
    awayScore: 2,
    minutesPlayed: 90,
    status: "Live",
    id: 9,
  },
  {
    home: "Team X",
    away: "Team Z",
    homeScore: 0,
    awayScore: 3,
    minutesPlayed: 70,
    status: "Finished",
    id: 10,
  },
];

export const leagueTableData = [
  {
    id: 1,
    position: 1,
    clubName: "Manchester United",
    played: 10,
    win: 8,
    draw: 1,
    lose: 1,
    goalDifference: 218,
    points: 25,
  },
  {
    id: 2,
    position: 1,
    clubName: "Club B",
    played: 10,
    win: 8,
    draw: 1,
    lose: 1,
    goalDifference: 18,
    points: 25,
  },
  {
    id: 3,
    position: 1,
    clubName: "Club C",
    played: 10,
    win: 8,
    draw: 1,
    lose: 1,
    goalDifference: 18,
    points: 25,
  },
  {
    id: 4,
    position: 1,
    clubName: "Club C",
    played: 10,
    win: 8,
    draw: 1,
    lose: 1,
    goalDifference: 18,
    points: 25,
  },
  {
    id: 5,
    position: 1,
    clubName: "Club C",
    played: 10,
    win: 8,
    draw: 1,
    lose: 1,
    goalDifference: 18,
    points: 25,
  },
  {
    id: 6,
    position: 1,
    clubName: "Club C",
    played: 10,
    win: 8,
    draw: 1,
    lose: 1,
    goalDifference: 18,
    points: 25,
  },
  {
    id: 7,
    position: 1,
    clubName: "Club C",
    played: 10,
    win: 8,
    draw: 1,
    lose: 1,
    goalDifference: 18,
    points: 25,
  },
  {
    id: 8,
    position: 1,
    clubName: "Club C",
    played: 10,
    win: 8,
    draw: 1,
    lose: 1,
    goalDifference: 18,
    points: 25,
  },
  {
    id: 9,
    position: 1,
    clubName: "Club C",
    played: 10,
    win: 8,
    draw: 1,
    lose: 1,
    goalDifference: 18,
    points: 25,
  },
  {
    id: 10,
    position: 1,
    clubName: "Club C",
    played: 10,
    win: 8,
    draw: 1,
    lose: 1,
    goalDifference: 18,
    points: 25,
  },
  {
    id: 11,
    position: 1,
    clubName: "Club C",
    played: 10,
    win: 8,
    draw: 1,
    lose: 1,
    goalDifference: 18,
    points: 25,
  },
  {
    id: 12,
    position: 1,
    clubName: "Club C",
    played: 10,
    win: 8,
    draw: 1,
    lose: 1,
    goalDifference: 18,
    points: 25,
  },
  {
    id: 13,
    position: 1,
    clubName: "Club C",
    played: 10,
    win: 8,
    draw: 1,
    lose: 1,
    goalDifference: 18,
    points: 25,
  },
  {
    id: 14,
    position: 1,
    clubName: "Club C",
    played: 10,
    win: 8,
    draw: 1,
    lose: 1,
    goalDifference: 18,
    points: 25,
  },
];
